#!/bin/bash
# Ask before pushing to remote master branch

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${remote_ref##refs/heads/}" = "master" ]]
  then
    # Allows us to read user input below, assigns stdin to keyboard
    exec < /dev/tty

    while read -p "Are you sure to push to master branch? [y/n] " answer
    do
      case $answer in
      y)
        echo pushing to master...
        break
        ;;
      n)
        exit 1
        ;;
      *)
        echo "Please answer y or n"
        ;;
      esac
    done
  fi
done
